apiVersion: autoscaling/v2
kind: ScaledObject
metadata:
  name: cpuscalersdo
spec:
  scaleTargetRef:
    name: sdodev
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      type: Utilization
      value: "50"
      containerName: sdowebsite