apiVersion: autoscaling/v2
kind: ScaledObject
metadata:
  name: cpuscalersdo
  namespace: sdodev
spec:
  scaleTargetRef:
    name: sdo
  pollingInterval: 20
  cooldownPeriod:  30
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: cpu
    metricType: Utilization
    metadata:
      type: Utilization
      value: "80"
