apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: sdoqa=delsynn/sdo:qa
    argocd-image-updater.argoproj.io/sdoqa.update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: qa
  name: sdoqa
  namespace: argo
spec:
  destination:
    namespace: sdoqa
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Cloud-Computing-2324/evaluation-smoothdevoperators.git
    path: k8sqa
    targetRevision: qa
  info:
    - name: 'sdoqa'
      value: 'https://sdoqa.38.cc.ucll.cloud'

