apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: sdodev=delsynn/sdo:qa
    argocd-image-updater.argoproj.io/sdodev.update-strategy: digest
    argocd-image-updater.argoproj.io/git-branch: qa
  name: sdoqa
  namespace: argo
spec:
  destination:
    namespace: sdoqa
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Cloud-Computing-2324/evaluation-smoothdevoperators.git
    path: overlays/qa
    targetRevision: qa
  info:
    - name: 'sdoqa'
      value: 'https://sdoqa.38.cc.ucll.cloud'
  syncPolicy:  
    automated:  
      prune: true
      selfHeal: true
