apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: qa

resources:
- ../../base
- rollout.yaml
- rolloutservice.yaml
- promscaler.yaml
- nginxExporterDeployment.yaml

patchesStrategicMerge:
- patchDeployment.yaml