apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdo
  namespace: sdoqa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdoqa
  template:
    metadata:
      labels:
        app: sdoqa
    spec:
      containers:
      - name: sdowebsite
        image: delsynn/sdo:qa
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdo
  namespace: sdoqa
spec:
  rules:
  - host: sdoqa.38.cc.ucll.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdo
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: sdo
  namespace: sdoqa
spec:
  selector:
    app: sdoqa

