server:
  ingress:
    enabled: true
    hosts:
      - prometheus.example.com
  persistentVolume:
    enabled: false


additionalScrapeConfigs:

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['prometheus-nginx-exporter:9113']