apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdomain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdomain
  template:
    metadata:
      labels:
        app: sdomain
    spec:
      containers:
      - name: sdomain
        image: delsynn/sdo:latest
        ports:
        - containerPort: 80