apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdomain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdomain
  template:
    metadata:
      labels:
        app: sdomain
    spec:
      containers:
      - name: sdomain
        image: delsynn/sdo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m" # This means 0.1 CPU unit
            memory: "64Mi" # This means 64 Mebibytes of memory
          limits:
            cpu: "500m" # This means 0.5 CPU unit
            memory: "128Mi" # This means 128 Mebibytes of memory