apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    argocd.argoproj.io/instance: sdomain
  name: rollouts
  namespace: sdomain
spec:
  selector:
    matchLabels:
      app: sdomain
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 80
      - pause: {}
      - setWeight: 100
  template:
    metadata:
      labels:
        app: sdomain
    spec:
      containers:
        - image: delsynn/sdo:main
          name: sdomain
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 32Mi


