apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    argocd.argoproj.io/instance: sdomain
  name: rollouts
  namespace: sdomain
spec:
  selector:
    matchLabels:
      app: sdomain
  replicas: 3
<<<<<<< HEAD
  selector:
    matchLabels:
      app: sdomain
  template:
    metadata:
      labels:
        app: sdomain
    spec:
      containers:
      - name: rollouts
        image: delsynn/sdo:main
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
=======
>>>>>>> e06305f3614e1708dc19aba1eeb02190c4ed3b00
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 80
      - pause: {}
      - setWeight: 100
  template:
    metadata:
      labels:
        app: sdomain
    spec:
      containers:
        - image: delsynn/sdo:main
          name: sdomain
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 32Mi


