apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: sdomain=delsynn/sdo:latest
    argocd-image-updater.argoproj.io/sdomain.update-strategy: digest
    argocd-image-updater.argoproj.io/git-branch: main
  name: sdomain
  namespace: argo
spec:
  destination:
    namespace: sdomain
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Cloud-Computing-2324/evaluation-smoothdevoperators.git
    path: overlays/k8smain
    targetRevision: HEAD
  info:
    - name: 'sdomain'
      value: 'https://sdomain.38.cc.ucll.cloud'