apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: sdomain=delsynn/sdo:latest
    argocd-image-updater.argoproj.io/sdomain.update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-method: git
  name: {{ .Values.appName }}
  namespace: argo
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Cloud-Computing-2324/evaluation-smoothdevoperators.git
    path: overlays/main
    targetRevision: HEAD
  info:
    - name: 'sdomain'
      value: 'https://sdomain.38.cc.ucll.cloud'
  syncPolicy:  
    automated:  
      prune: true
      selfHeal: true