apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpuscalersdo
  namespace: sdodev
spec:
  scaleTargetRef:
    name: sdo
  pollingInterval: 20
  cooldownPeriod:  30
  minReplicaCount: 1
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      type: Utilization
      value: "80"