apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.appName }}-cronscaler
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.appName }}
  minReplicaCount: 1
  pollingInterval: 20
  cooldownPeriod:  30
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Brussels
      start: 0 8 * * *
      end: 0 20 * * *
      desiredReplicas: "2"