apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-rolloutservice
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.appName }}