apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: sdodev=docker.io/delsynn/sdo:dev
    argocd-image-updater.argoproj.io/sdodev.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/git-branch: dev
    argocd-image-updater.argoproj.io/include-globs: 'k8sdev/*.yaml'
  name: sdodev
  namespace: argo
spec:
  destination:
    namespace: sdodev
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: k8sdev
    repoURL: https://github.com/Cloud-Computing-2324/evaluation-smoothdevoperators.git
    targetRevision: dev
  info:
    - name: 'sdodev'
      value: 'https://sdodev.38.cc.ucll.cloud'

