apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: sdodev
  patch: |-
    spec:
      template:
        metadata:
          labels:
            app: sdodev
        spec:
          containers:
          - name: sdodev
            image: delsynn/sdo:dev
            imagePullPolicy: Always
            ports:
            - containerPort: 80

- target:
    kind: Application
    name: sdodev
  patch: |-
    spec:
      destination:
        namespace: sdodev
      source:
        path: k8sdev
        targetRevision: dev
      info:
      - name: 'sdodev'
        value: 'https://sdodev.38.cc.ucll.cloud'

- target:
    kind: Ingress
    name: sdodev
  patch: |-
    spec:
      rules:
      - host: sdodev.38.cc.ucll.cloud
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sdodev
                port:
                  number: 80

- target:
    kind: Service
    name: sdodev
  patch: |-
    spec:
      selector:
        app: sdodev
      ports:
      - protocol: TCP
        port: 80
        targetPort: 80
