apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: sdoqa
  patch: |-
    spec:
      template:
        metadata:
          labels:
            app: sdoqa
        spec:
          containers:
          - name: sdoqa
            image: delsynn/sdo:qa
            imagePullPolicy: Always
            ports:
            - containerPort: 80

- target:
    kind: Application
    name: sdoqa
  patch: |-
    spec:
      destination:
        namespace: sdoqa
      source:
        path: k8sqa
        targetRevision: qa
      info:
      - name: 'sdoqa'
        value: 'https://sdoqa.38.cc.ucll.cloud'

- target:
    kind: Ingress
    name: sdoqa
  patch: |-
    spec:
      rules:
      - host: sdoqa.38.cc.ucll.cloud
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sdoqa
                port:
                  number: 80

- target:
    kind: Service
    name: sdoqa
  patch: |-
    spec:
      selector:
        app: sdoqa
      ports:
      - protocol: TCP
        port: 80
        targetPort: 80
