apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-scaledobject
  namespace: sdomain
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sdomain
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50