apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdomain
  namespace: argo
spec:
  destination:
    namespace: sdomain
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/main
    repoURL: https://github.com/Cloud-Computing-2324/evaluation-smoothdevoperators.git
    targetRevision: HEAD
  info:
    - name: 'sdomain'
      value: 'https://sdomain.38.cc.ucll.cloud'

