apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdo
spec:
  selector:
    matchLabels:
      app: sdodev
  template:
    metadata:
      labels:
        app: sdodev
    spec:
      containers:
      - name: sdowebsite
        image: delsynn/sdo:dev
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdo
spec:
  rules:
  - host: sdodev.38.cc.ucll.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdo
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: sdo
spec:
  selector:
    app: sdodev

