apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: website-http-route
  namespace: default
spec:
  parentRefs:
    - name: website-gateway
  hostnames:
    - "website.47.cc.ucll.cloud"  # Replace with your domain
  rules:
    - backendRefs:
      - name: website-more-traffic
        port: 80
        weight: 70
      - name: website-less-traffic
        port: 80
        weight: 30