name: Build and Deploy Website

on:
  push:
    branches:
      - qa

jobs:
  build-upload-download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2    

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          # mdbook-version: '0.4.10'

      - run: mdbook build

      - name: Upload mdBook Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mdbook-artifact
          path: book

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download mdBook Artifact
        uses: actions/download-artifact@v2
        with:
          path: website