name: Build and Deploy Website

on:
  push:
    branches:
      - qa
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          # mdbook-version: '0.4.10'

    - run: mdbook build

    - name: Archive mdBook
      uses: actions/upload-artifact@v2
      with:
        name: mdbook-artifact
        path: book

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download mdBook Artifact
      uses: actions/download-artifact@v2
      with:
        name: mdbook-artifact

    - name: Copy Files to Website Folder
      run: |
        cp -r book/* website/