name: Build QA

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      # node.js installeert npx dependency om tests te kunnen gebruiken
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
          # mdbook-version: '0.4.10'
  
      - name: setup markdown link check
        run: npm install markdown-link-check@3.11.2

      - name: Check for broken links
        run: npx markdown-link-check **/*.md 
        continue-on-error: true

      - name: setup markdownlint
        run: npm install markdownlint-cli

      - name: check for markdown linting errors
        run: npx markdownlint **/*.md
        continue-on-error: true

      - name: setup spellcheck
        run: npm install markdown-spellcheck

      # spellchecker lijkt nog niet te werken, heeft blijkbaar manuele correctie nodig  
      - name: check for spelling errors
        run: npx markdown-spellcheck **/*.md
        continue-on-error: true
        
      - run: mdbook build
      - run: mdbook test
        continue-on-error: true

      - name: Docker login
        env:
          DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
        run: |
          echo 'Docker login'
          docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_SECRET

      - name: Build and push Docker image
        run: |
          echo 'Running build...'
          docker build --no-cache ./book -t delsynn/sdo:qa
          echo 'Pushing image...'
          docker push delsynn/sdo:qa
          echo 'Done !'