name: Manual Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Renovate
      run: npm install -g renovate

    - name: Run Renovate
      run: renovate --config-file .github/renovate.json